### ISSUE TITLE
Cross compile ros stopped working

### ISSUE THREAD

**Issue by sherwood333** [HesselM/rpicross_notes#12]
Following your tutorial today to create a ross cross complile VM. Trying to cross compile gives me an error

> ./src/catkin/bin/catkin_make_isolated -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/cross/rpicross_notes/rpi-generic-toolchain.cmake
> Traceback (most recent call last):
>  File "./src/catkin/bin/catkin_make_isolated", line 12, in <module>
>    from catkin.builder import build_workspace_isolated
>  File "./src/catkin/bin/../python/catkin/builder.py", line 66, in <module>
>    from catkin_pkg.terminal_color import ansi, disable_ANSI_colors, fmt, sanitize
>ImportError: No module named terminal_color

if I edit the builder.py to say `from catkin_pkg.terminal_color import ansi, disable_ANSI_colors, fmt, sanitize` instead, it fails to build with `ImportError: cannot import name ansi'

Any help would be appreciated.

**Comment by HesselM** [comment]
Hm, your issue states two things:
- the code shows "ImportError: No module named terminal_color"
- whereas you state "ImportError: cannot import name ansi"

Have you seen [this issue](https://github.com/ros/catkin/issues/956) ? It might provide some pointers

**Comment by HesselM** [comment]
Any updates on this?
